runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static


- url: .*
  script: main.app

libraries:
- name: PIL
  version: "1.1.7"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

inbound_services:
- mail
