runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static

#- url: /_ah/mail/.+
#  script: handle_incoming_email.app
#  login: admin

- url: .*
  script: main.app


libraries:
- name: PIL
  version: "1.1.7"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

